src/GLPK.jl, test/glpk_tst_2.jl, test/glpk_tst_3.jl, test/glpk_tst_4.jl, test/glpk_tst_5.jl, test/glpk_tst_6.jl
this allows installing in a non-default location
=> Use relative paths instead of Pkg.dir("GLPK")

deps/build.jl
Fixes deprecations on `Julia v0.5`. There still are few deprecations, but I guess they are coming from `BinDeps` while doing a `Pkg.build("GLPK")`.
=> fix deprecations

deps/build.jl
`WORD_SIZE` -> `Sys.WORD_SIZE`. Works on 0.3, 0.4, and 0.5.
=> Fix the WORD_SIZE dep warn

.travis.yml, REQUIRE, appveyor.yml, src/GLPK.jl
There's this one depwarn I'm not able to identify:
```
WARNING: deprecated syntax "param.(s) = ...".
Use "setfield!(param, s, ...)" instead.
```
Do you know where this is coming from?
=> More dep warn fixes, remove 0.3, add 0.5 support

deps/build.jl, deps/verreq.jl, test/glpk_tst_5.jl, test/runtests.jl
I checked all the release notes and didn't find any API changes. Nevertheless one of the tests involving the SAT solver is not working, see the upcoming travis failures.
CC @carlobaldassi @tkelman
=> bump to GLPK 4.61 on linux

test/glpk_tst_5.jl
I forgot to add this check. In fact this is not covered by Travis or AppVeyor since only AppVeyor has 32 bits but the GLPK version for Windows is below v4.57.
=> Add a check for word size in test_5

deps/verreq.jl, test/glpk_tst_5.jl
My Manjaro box just received the recently released libglpk 4.62
Looks like something the MiniSat solver is now supported (based on the test that I had to chage). 
Tests are passing on my system.
=> add support for libglpk 4.62

.travis.yml, REQUIRE, appveyor.yml, deps/build.jl
I'm getting a segfault when running the tests, but by dropping 0.5 we can at least run femtocleaner to fix some deprecations.
=> drop support for julia 0.5 and fix build on 0.7

LICENSE.md, REQUIRE, appveyor.yml, deps/.gitignore, src/MOIWrapper.jl, src/infeasibility_certificates.jl, test/MOIWrapper.jl, test/REQUIRE, test/glpk_tst_1.jl, test/runtests.jl
Now that things are settling down, I'm going through and cleaning up the MOIWrapper. Initially lots of functions had been copied from the MPB wrapper with some adjustments so there was weird code style. 
**The largest change is that it now defines a single (un-exported) `GLPK.Optimizer()` object.**
LQOI and GLPK now decide which methods to call based on whether there are integer variables or not. This switch is now done at run-time rather than compile time, but it isn't too much of a biggie as we already had a switch for the different LP solution methods.
<s>Currently passes MOI except for the `ModelLike` tests with a weird `"access to undefined reference"` error.</s>
Closes #54 
Closes #57
=> RFC: updates for MOI 0.5

src/MOIWrapper.jl, test/MOIWrapper.jl
Ref: https://github.com/JuliaOpt/LinQuadOptInterface.jl/issues/43
=> Pass the objective constant directly to the solver instead of caching it

.travis.yml
16 travis combinations is a bit excessive and clogs up the JuliaOpt queue. I don't recall ever finding a bug related to clang vs gcc.
@rdeits
=> Remove nightly and compiler builds from travis

.travis.yml
In the interest of reducing our travis usage and backlog, this turns off push builds except for master and any `release-` branches we might want to make.
=> Don't run the Travis build on every push to every branch 

appveyor.yml
It's confusing to leave CI in a broken state.
=> Allow failure on AppVeyor for x86, 0.7+

README.md
This goes out of date quickly. The CI configs provide the same information.
=> Remove out of date testing status

src/MOIWrapper.jl, test/MOIWrapper.jl
The problem is that `intopt` requires a starting LP basis, but the problem is unbounded. This is likely an issue with the MPB solver as well, but given that no one has reported the issue, I didn't investigate.
Closes #79
=> Fix issues with infeasible and unbounded integer models.

deps/.gitignore, src/MOIWrapper.jl, test/MOIWrapper.jl
We need to loop through and collect upper and lower terms, otherwise we can end up trying to set
variable bounds with lower > upper.
See also https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/66
=> Fix handling of setting variable bounds. 

src/MOIWrapper.jl
Fix deprecated `warn` in MOIWrapper.jl. (https://github.com/JuliaOpt/GLPK.jl/issues/88)
This raised an `UndefVarError` when an invalid option was passed to `GLPK.Optimizer`
Before: see https://github.com/JuliaOpt/GLPK.jl/issues/88
After:
```julia
julia> Model(with_optimizer(GLPK.Optimizer, XXX=1))
┌ Warning: Ignoring option: XXX => 
└ @ GLPK ~/.julia/dev/GLPK/src/MOIWrapper.jl:117    
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: GLPK
```
=> Fix deprecated warn

README.md, src/MOI_wrapper.jl, test/MOI_wrapper.jl
Bugfix for #110 
Is their also the desired behavior of getting back `nothing` when `TimeLimitSec` was called with `nothing` or is it okay to return a high number?
=> bugfix for TimeLimitSec and tests

Project.toml, src/MOI_callbacks.jl, test/MOI_callbacks.jl
Now that callbacks can be used in JuMP's Automatic mode, we need to tell `copy_to` to pass them to the inner optimizer. 
x-ref https://github.com/JuliaOpt/JuMP.jl/issues/2124
=> Add missing supports

.travis.yml, Project.toml
=> Test on Julia 1.2 and 1.3

.travis.yml, Project.toml, src/GLPK.jl, test/glpk_tst_6.jl
Try out a JLL build of GLPK.
<s>I get a weird error: `ios_del_row` now fails.
```Julia
(GLPK) pkg> test GLPK
Testing GLPK
Resolving package versions...
Assertion failed: 0
Error detected in file draft/glpios01.c at line 1552
glpk_tst_6.jl: Error During Test at /Users/oscar/.julia/dev/GLPK/test/glpk_tst_6.jl:87
Test threw exception
Expression: GLPK.intopt(mip, params) == 0
GLPKFatalError("GLPK call failed. All GLPK objects you defined so far are now invalidated.")
Stacktrace:
[1] _err_hook(::Ptr{Nothing}) at /Users/oscar/.julia/dev/GLPK/src/GLPK.jl:214
[2] ios_del_row(::Ptr{Nothing}, ::Int32) at /Users/oscar/.julia/dev/GLPK/src/GLPK.jl:220
[3] cb_callback(::Ptr{Nothing}, ::Ptr{Nothing}) at /Users/oscar/.julia/dev/GLPK/test/glpk_tst_6.jl:49
[4] intopt(::Prob, ::IntoptParam) at …
```
=> Move to jll build of GLPK

test/MOI_wrapper.jl
With the new bridges for Semiinteger and Semicontinuous, `OPTIMIZER` now supports these sets. However, as they are bridged, GLPK does not see them as bounds hence no error is thrown so this tests fails with the bridges. To fix the tests with MOI master, GLPK is passed without any bridges.
=> Run test for setting bounds twice without bridges

Project.toml, perf/runbench.jl, src/GLPK.jl, src/MOI_wrapper/MOI_copy.jl, src/MOI_wrapper/MOI_wrapper.jl, test/MOI_wrapper.jl
Following the lines of https://github.com/jump-dev/Clp.jl/pull/94
Add a batch copy, it seems that the batch is not much better than one-by-one for GLPK.
Running the runbench.jl file from the perf folder.
Before this PR we had:
```
──────────────────────────────────────────────────────────────────
Time                   Allocations
──────────────────────   ───────────────────────
Tot / % measured:       143s / 100%            30.4GiB / 100%
Section   ncalls     time   %tot     avg     alloc   %tot      avg
──────────────────────────────────────────────────────────────────
bcs + v      100    32.9s  23.0%   329ms   7.23GiB  23.8%  74.0MiB
build      100    18.8s  13.1%   188ms   7.22GiB  23.7%  73.9MiB
opt        100    13.8s  9.66%   138ms   7.64MiB  0.02%  78.2KiB
cs           100 …
```
=> Add specialized copy method

src/MOI_wrapper/MOI_wrapper.jl
The MOI wrapper is currently failing on 32 bits due to
https://github.com/jump-dev/MathOptInterface.jl/blob/21fd61cc906662834866b287dc15c628723fee34/src/Utilities/CleverDicts.jl#L169
See https://ci.appveyor.com/project/JuliaPolyhedra/polyhedra-jl/builds/35315395/job/lh2158kp2srcxc8l
=> Fix use of CleverDict for 32-bits

Project.toml, src/MOI_wrapper/MOI_wrapper.jl, src/MOI_wrapper/infeasibility_certificates.jl, test/MOI_wrapper.jl
Follows https://github.com/jump-dev/Gurobi.jl/pull/363
This also changes how we compute infeasibility certificates. We now directly solve the dual and obtain an unbounded ray, instead of simply aggregating violated constraints. The previous behavior generated a valid infeasibility certificate, but it didn't match the Farkas-type results in the tests.
=> Add infeasibility certificate for variable bounds

src/MOI_wrapper/infeasibility_certificates.jl
I didn't have #155 quite right, but the extra unit tests I added to MOI were much more thorough. It isn't sufficient to check the sign, because the (infeasible) primal solution might be `0.0`, offering no information on which way to go.
=> Fix sign errors in Farkas dual when solution is degenerate

README.md, src/MOI_wrapper/MOI_wrapper.jl, test/MOI_wrapper.jl
Closes #163 
I looked into #163. The issue was the model was numerically infeasible. GLPK detected this quickly, but then we tried to solve the dual in order to find an infeasibility certificate. Due to the numerics, this solve was taking a long time. 
It seems like the easiest solution was just to provide a flag to generate the certificates.
cc @yuexiao-marketingattribution
=> Add want_infeasibility_certificates flag

src/MOI_wrapper/MOI_wrapper.jl, test/MOI_wrapper.jl
Avoids a truncation error then Julia attempts to cast a value that exceeds the typemax to a Cint.
Closes #167
=> Cap TimeLimitSec to typemax(Int32)

src/MOI_wrapper/MOI_wrapper.jl, test/MOI_wrapper.jl
Previous code assumed someone would pass a "nice" time limit that was an integer number of milliseconds, not something like `1.234567` seconds.
=> Handle fractional number of ms in TimeLimitSec

src/GLPK.jl, src/precompile.jl
See: https://github.com/jump-dev/JuMP.jl/pull/2484
=> Add precompilation directives

Project.toml, src/MOI_wrapper/MOI_copy.jl, test/MOI_wrapper.jl
JuMP docs in https://github.com/jump-dev/JuMP.jl/pull/2610 were still failing, which identified a few other bugs that #183 didn't catch.
=> Rewrite MOI.copy_to to simplify and fix various bugs

src/MOI_wrapper/MOI_copy.jl, test/MOI_callbacks.jl, test/MOI_wrapper.jl
This fixes a couple of other bugs in `MOI.copy_to`. We weren't setting integrality, and GLPK doesn't like empty models.
This PR also improves the testing. Lesson learned: if JuMP rolls out direct copies, we need the solvers to much more thoroughly test their `copy_to` functions via a CachingOptimizer.
=> More fixes to copy_to

Project.toml, perf/runbench.jl, src/GLPK.jl, src/MOI_wrapper/MOI_copy.jl, src/MOI_wrapper/MOI_wrapper.jl, src/MOI_wrapper/deprecated_constants.jl, src/precompile.jl, test/MOI_callbacks.jl, test/MOI_wrapper.jl, test/runtests.jl
This PR updates GLPK to MOI v0.10.
Closes #148
=> Breaking changes for MOI 0.10.0

src/MOI_wrapper/MOI_wrapper.jl
Updated for https://github.com/jump-dev/MathOptInterface.jl/pull/1660
```Julia
julia> MOI.Test.runtests(
model, 
config, 
include=["test_unbounded_", "test_infeasible_"],
)
Test Summary:             | Pass  Total
test_infeasible_MAX_SENSE |    5      5
Test Summary:                    | Pass  Total
test_infeasible_MAX_SENSE_offset |    5      5
Test Summary:             | Pass  Total
test_infeasible_MIN_SENSE |    5      5
Test Summary:                    | Pass  Total
test_infeasible_MIN_SENSE_offset |    5      5
Test Summary:                    | Pass  Total
test_infeasible_affine_MAX_SENSE |    5      5
Test Summary:                           | Pass  Total
test_infeasible_affine_MAX_SENSE_offset |    5      5
Test Summary:                    | Pass  Total …
```
=> WIP: Fix for infeasibility certificates

Project.toml
@staticfloat has already rebuild GLPK_jll for the M1: https://github.com/JuliaPackaging/Yggdrasil/pull/3630
Closes #199
=> Bump supported GLPK_jll version

src/MOI_wrapper/MOI_copy.jl
Part of https://github.com/jump-dev/JuMP.jl/issues/2817
If we include https://github.com/jump-dev/MathOptInterface.jl/pull/1704
Script
```Julia
using MathOptInterface
const MOI = MathOptInterface
using GLPK
function create_model(I, T = 10000)
model = MOI.Utilities.Model{Float64}()
v = MOI.VariableIndex[]
for _ in 1:I
x = MOI.add_variables(model, T)
MOI.add_constraint.(model, x, MOI.GreaterThan(0.0))
MOI.add_constraint.(model, x, MOI.LessThan(100.0))
for t in 2:T
f = MOI.ScalarAffineFunction(
MOI.ScalarAffineTerm.([1.0, -1.0], [x[t], x[t-1]]),
0.0,
)
MOI.add_constraint(model, f, MOI.GreaterThan(-10.0))
MOI.add_constraint(model, f, MOI.LessThan(10.0))
end
append!(v, x)
end
g = MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(1.0, v), 0.0)
MOI.set(model, MOI.ObjectiveSense(), MOI.MIN_SENSE) …
```
=> Improve performance of MOI.copy_to

src/MOI_wrapper/MOI_wrapper.jl
`MOI.SUPERBASIC` is not defined. Looks like it's `SUPER_BASIC` (see https://github.com/jump-dev/MathOptInterface.jl/blob/d281d6394ff5c3b29b5da1cb8a05acb80ed1d637/src/attributes.jl#L1308 MOI v1.1.0).
=> MOI.SUPERBASIC -> MOI.SUPER_BASIC

src/MOI_wrapper/MOI_wrapper.jl, test/MOI_wrapper.jl
I think we had `GLP_NS` and `GLP_NF` around the wrong way. Raised by @guimarqu in https://github.com/jump-dev/GLPK.jl/pull/213
Here's the paragraph from the manual: http://most.ccib.rutgers.edu/glpk.pdf
`GLP_NF` is a non-basic free variable which corresponds to our super-basic.
I also added a test which returns at least one of each status, but it's probably quite fragile between GLPK versions because the model has lots of weirdness.
=> Fix VariableBasisStatus and add test

src/MOI_wrapper/MOI_wrapper.jl, test/MOI_wrapper.jl
This is a follow-up from https://github.com/jump-dev/MathOptInterface.jl/pull/1800
It significantly improved the performance of updates. Using the same code from the PR above:
```julia
julia> @btime update_parameters_multiple_times_with_single_change(num_variables, num_solves)
9.115 s (255872 allocations: 2.81 GiB)
julia> @btime update_parameters_multiple_times_with_multiple_changes(num_variables, num_solves)
2.522 ms (5800 allocations: 2.33 MiB)
```
Modifying multiple objective coefficients isn't available in GLPK
=> Add MOI.modify for multiple changes at once

README.md
Closes https://github.com/jump-dev/GLPK.jl/issues/225
cc @Zinoex is this sufficient?
=> [README] add note on thread-safety

src/MOI_wrapper/MOI_wrapper.jl, test/MOI_callbacks.jl
Closes #232
Now gives:
```Julia
julia> using GLPK; import MathOptInterface as MOI
julia> model = GLPK.Optimizer()
A GLPK model
julia> x = MOI.add_variable(model)
MOI.VariableIndex(1)
julia> MOI.add_constraint(model, x, MOI.ZeroOne())
MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, MathOptInterface.ZeroOne}(1)
julia> my_callback(args...) = error("FooBar")
my_callback (generic function with 1 method)
julia> MOI.set(model, GLPK.CallbackFunction(), my_callback)
julia> MOI.optimize!(model)
ERROR: FooBar
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] my_callback(args::GLPK.CallbackData)
@ Main ./REPL[5]:1
[3] (::GLPK.var"#17#18"{GLPK.Optimizer, typeof(my_callback)})(cb_data::GLPK.CallbackData)
@ GLPK ~/.julia/dev/GLPK/src/MOI_wrapper/MOI_callbacks.jl:31
[4] …
```
=> Improve stacktrace of errors thrown from within a callback
