.travis.yml
REQUIRE
appveyor.yml
src/GLPK.jl
test/glpk_tst_4.jl

Fix deprecation warnings on julia 0.6

---

deps/build.jl

https://github.com/staticfloat/homebrew-juliadeps/issues/117

bump to glpk 4.61 homebrew binary

---

src/GLPK.jl

Enable precompilation #27

---

src/GLPK.jl
src/GLPK_checks.jl
test/glpk_tst_6.jl

I didn't fix the deprecations that were awkward (like `using SparseArrays`).

fix many deprecations on 0.7, passes tests

---

.travis.yml
REQUIRE
appveyor.yml
deps/build.jl
src/GLPK.jl
src/MOIWrapper.jl
test/MOIWrapper.jl
test/REQUIRE
test/glpk_tst_6.jl
test/runtests.jl

Also reactivates tests on 0.7.
This needs the fixes in https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/36 to work.

Fixes for julia 0.7

---

.travis.yml
appveyor.yml
deps/build.jl

Fixes #62. Tested locally on OSX with Julia 1.0.

Fix build on Julia 1.0.

---

REQUIRE
src/MOIWrapper.jl
test/MOIWrapper.jl

DNMY: update LQOI

---

REQUIRE
src/MOIWrapper.jl
test/MOIWrapper.jl

DNMY: Update to LQOI 0.6

---

.gitignore
.travis.yml
Project.toml
README.md
REQUIRE
appveyor.yml
src/GLPK.jl
src/MOI_wrapper.jl
test/MOI_wrapper.jl
test/glpk_tst_1.jl
test/glpk_tst_2.jl
test/glpk_tst_3.jl
test/glpk_tst_4.jl
test/glpk_tst_5.jl
test/glpk_tst_6.jl
test/runtests.jl

Closes https://github.com/JuliaOpt/GLPK.jl/issues/94

Remove REQUIRE and support for Julia v0.6 and v0.7 and add Project.toml

---

README.md
deps/build.jl
deps/build_GMP.v6.1.2.jl

Update platform_key -> platform_key_abi as in #97 and custom binary install with `ENV["JULIA_GLPK_LIBRARY_PATH"]`

Update BinaryBuilder and Custom Install

---

Project.toml

Bump to 0.11.3

---

src/MOI_wrapper.jl
test/MOI_wrapper.jl

[MOI] Handle parameters properly

---

src/infeasibility_certificates.jl
test/MOI_wrapper.jl

Call GLPK.factorize when computing infeasibility certificates

---

src/MOI_wrapper.jl
test/MOI_wrapper.jl

Follow the lead of: https://github.com/JuliaOpt/Gurobi.jl/pull/251

Update handling of duplicate names

---

src/MOI_callbacks.jl

See https://github.com/JuliaOpt/MathOptInterface.jl/pull/959

Callbacks are model attributes

---

Project.toml

Attempt to make CEnum dependency consistent with other solvers, so the solvers can co-exist in same environment.

Bump CEnum to 0.4

---

src/GLPK.jl

We should check the user's binary version, instead of the version in `libglpk_common.jl`...

Update version check and error message

---

Project.toml
src/MOI_wrapper/MOI_callbacks.jl
test/MOI_callbacks.jl

Test will fail until #161 is merged, so this is just a draft.
Closes #160 
Also address #146

Add CallbackNodeStatus

---

Project.toml
src/MOI_wrapper/MOI_wrapper.jl

Copy https://github.com/jump-dev/Gurobi.jl/pull/385

Make CleverDict a concrete type

---

src/MOI_wrapper/MOI_wrapper.jl
test/MOI_callbacks.jl

x-ref https://github.com/jump-dev/CPLEX.jl/pull/354
x-ref https://github.com/jump-dev/Gurobi.jl/pull/394

Allow broadcasting in callbacks

---

scripts/Project.toml
scripts/clang.jl
src/GLPK.jl
src/gen/libglpk_api.jl
src/gen/libglpk_common.jl
test/glpk_tst_4.jl

Bump GLPK_jll to v5.0

---

Project.toml
test/glpk_tst_6.jl

Oops! Looks like I missed that file locally somehow.
cc @GregPlowman

Bump GLPK_jll version in Project.toml

---

README.md

The argument should be a zero-argument anonymous function

Fix missing bracket in README.md

---

src/MOI_wrapper/MOI_wrapper.jl
test/MOI_wrapper.jl

Change default print level

---

src/MOI_wrapper/MOI_copy.jl
test/MOI_wrapper.jl

Found as part of https://github.com/jump-dev/JuMP.jl/pull/2610

Fix index_map in MOI.copy_to

---

src/MOI_wrapper/MOI_wrapper.jl
test/MOI_wrapper.jl

Closes #181 
This reverts commit c32c1895c19b309713d375b1f919b130163d28f6.
I'm reverting this change because it is too disruptive to the ecosystem. 
The JuMP examples just turn into a mess of printing, and having to add `set_silent` to every example is a pain.
When users ask for printing by default, they don't want to see this:
```Julia
[ Info: writing result to `~/.julia/dev/JuMP/docs/src/tutorials/Mixed-integer linear programs/network_flows.md`
0: obj =   0.000000000e+00 inf =   1.800e+03 (2)
3: obj =   1.000000000e+05 inf =   0.000e+00 (0)
*     4: obj =   9.000000000e+04 inf =   0.000e+00 (0)
Dispatch of Generators: [1000.0, 300.0] MW
Dispatch of Wind: 200.0 MW
Wind spillage: 0.0 MW
Total cost: 90000.0$
0: obj =   0.000000000e+00 inf =   1.800e+03 (2)
3: obj =   7.500000000e+04 inf = …
```

Revert "Change default print level (#182)"

---

Project.toml
src/MOI_wrapper/infeasibility_certificates.jl
test/MOI_wrapper.jl

Fix certificate generation with empty constraint matrix

---

src/MOI_wrapper/MOI_wrapper.jl

As suggested by https://github.com/JuliaLang/julia/issues/42269
Closes #154

Refactor usage of cfunction to avoid closure

---

src/GLPK.jl
src/MOI_wrapper/MOI_callbacks.jl
src/MOI_wrapper/MOI_copy.jl
src/MOI_wrapper/MOI_wrapper.jl
test/MOI_callbacks.jl
test/MOI_wrapper.jl

* Rename private methods
* Remove unused methods
* Tidy tests to reflect recent changes in MOI

General code maintenance and fixes

---

src/MOI_wrapper/MOI_wrapper.jl
test/MOI_callbacks.jl

Fix issue 189

---

src/precompile.jl

Part of https://github.com/jump-dev/MathOptInterface.jl/issues/1313

Update  precompile statements

---

Project.toml
src/MOI_wrapper/MOI_wrapper.jl
test/MOI_wrapper.jl

x-ref: https://github.com/chriscoey/MOIPajarito.jl/issues/12

Fix bug with negative time limits

---

src/MOI_wrapper/MOI_wrapper.jl

Only focusing on the simplex one for now

status to func

---

src/MOI_wrapper/infeasibility_certificates.jl
test/MOI_wrapper.jl

Fix basis factorization fail in infeas certificates

---

src/MOI_wrapper/MOI_wrapper.jl

Refactor status dicts into functions

---

Project.toml

x-ref https://github.com/jump-dev/JuMP.jl/issues/2564

Update to MOI v1.0

---

src/MOI_wrapper/MOI_wrapper.jl

I got `UndefVarError: GLP_EFA not defined`...

Fix constant name

---

test/MOI_wrapper.jl

Test found by @schillic.
x-ref: #220

Add test for PR#220

---

Project.toml
src/MOI_wrapper/MOI_copy.jl
test/MOI_wrapper.jl

x-ref https://github.com/jump-dev/HiGHS.jl/pull/172
x-ref https://github.com/jump-dev/HiGHS.jl/pull/173

Fix copy_to with empty constraint rows
